server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ENC(RhSSG3M1L+pPuJK4OVHzl5LkWKa6UPeFM+npLlAGD6ftqaqlKHZXt0dS5bYpBPUoo1dAM2Nj9BCmbaop0W4cTxGjCh4QcePh6dmwj8CEWmFeD2McNC9A6Y5X4qrTXTJ+q+lAre+0nBJb7Iz56CmW2koSNFnsMkfSYhgbmJ5GMFHJK+8p4RsG0EBTdBnL4X8/svA2UovNIXCly06A2j9lNw==)
    username: ENC(kSbVij29Q5IxlMTyH1g0rw==)
    password: ENC(f2DZKexIllOKp9G6wKa2T+E/dqGcnngS)
    driver-class-name: com.mysql.cj.jdbc.Driver

jasypt:
  encryptor:
    password: ${encrypt_key}

springdoc:
  version: '1.0'
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: true
  default-produces-media-type: application/json

gpt:
  key1: ${gpt_key1:sk-nothing}
  key2: ${gpt_key2:sk-nothing}
  key3: ${gpt_key3:sk-nothing}
  key4: ${gpt_key4:sk-nothing}
  key5: ${gpt_key5:sk-nothing}
  timeout: 100