spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(LdZxw097H/2MiHz+AhWNMReiECFH9pyz04+/ABemlc+gF9zVYSEsHhDev/+/zhLF)
    password: ENC(UP1cUlHd6LRKtCd8n5iqv73mGcrQZnnzIYZQVG3IMJY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
