jwt:
  secret: ENC(vtXQqpFzmMOU0LEzZAtvTclmTvMLzhfmOaL4g9nK+Q0/40Ja4ZhlmabPN6GqNbnnhfw/IDdr0nMT1zRVhUlzIT3Qn2B6S3BGAre61WLcHvPhaHJXYijicCy11npKMfzhnSXmWixqUgU=)
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800
  one-time-token-validity-in-seconds: 300
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(P2r75Nd5Uc8qoiTbZ/cNgVLIdT98YCmX2G2eW57EabURtSqNuORt0Lphx4Tu7hLl)
            client-secret: ENC(8arlxbAVa36A/543oTgnu+05lGT1aXDNWrhTa/BM3dUau0pJTDt7+sKBieDJ4dQW)
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
