server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  version: '1.0'
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: false
  default-produces-media-type: application/json
