spring:
  redis:
    host: ENC(Dp+Ea0BelQyPHmZZoWqb0LQxh97odMjFW2H+HqmiyU1QD3ZNN/0Ok9Yn3vnEWLh2dJYZtOBVUBjuuTEt53w4vA==)
    port: 6379
    password: ENC(zxJdJPB1xsHpOtQYAXblc94BTP5q70+bKhDWVlrT2MPBk+/XZSojp3uFm7cXp6Je)
